config/routes.rb
Rails.application.routes.draw do
  resources :cards

  get 'home/index' => 'home#index'
  post 'home/check' => 'home#check'
  root 'home#index'

end

app/models/card.rb
class Card < ActiveRecord::Base
  before_create :add_days
  validates :original_text, :translated_text, presence: true
  validate :check_word_and_translation

  def check_word_and_translation
    errors.add("Слово и перевод должны отличаться") if original_text.mb_chars.lstrip.downcase == translated_text.mb_chars.lstrip.downcase
  end

  def add_days
    self.review_date = Time.now + 3.days
  end
  scope :need_to_review, ->{where("review_date <=?", 3.days.ago).where("original_text is not null").order("RANDOM()")}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def index
    @cards = Card.all
  end

  def show
    @card = Card.find(params[:id])
  end

  def new
    @card = Card.new
  end
 
  def edit
    @card = Card.find(params[:id])
  end

  def create
    @card = Card.new(card_params)
 
    if @card.save
      redirect_to @card
    else
      render 'new'
    end
  end

  def update
    @card = Card.find(params[:id])
 
    if @card.update(card_params)
      redirect_to @card
    else
      render 'edit'
    end
  end
 
  def destroy
    @card = Card.find(params[:id])
    @card.destroy
    redirect_to cards_path
  end
 
  private
    def card_params
      params.require(:card).permit(:original_text, :translated_text, :review_date)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @card = Card.need_to_review.first
  end

  def check
    result = CheckCard.call(params: card_params)
     if result.success?
       redirect_to root_url, notice: "Правильный перевод"
     else
       redirect_to root_path, notice: "Неправильный перевод, правильно так => #{result.translation}"
     end
   end
  private def card_params
    params.permit(:card_id, :translated_text)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cards/_form.html.erb
<%= form_for @card do |f| %>

  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2>
        Вы не можете сохранить эту карточку:
      </h2>
      <ul>
        <% @card.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :original_text %><br>
    <%= f.text_field :original_text %>
  </p>
 
  <p>
    <%= f.label :translated_text %><br>
    <%= f.text_field :translated_text %>
  </p>

  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/cards/edit.html.erb
<h1>Редактировать карточку</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<h1>Все карточки</h1>
<table>
  <tr>
    <th>Слово</th>
    <th>Перевод</th>
    <th>Дата пересмотра</th>
    <th colspan="3"></th>
  </tr>
 
  <% @cards.each do |card| %>
    <tr>
      <td><%= card.original_text %></td>
      <td><%= card.translated_text %></td>
      <td><%= card.review_date %></td>
      <td><%= link_to "Show", card_path(card) %></td>
      <td><%= link_to "Edit", edit_card_path(card) %></td>
      <td><%= link_to "Destroy", card_path(card), method: :delete, data: { confirm: "Вы уверены?" } %></td>
    </tr>
  <% end %>
</table>

app/views/cards/new.html.erb
<h1>Новая карточка</h1>

<%= render 'form' %>
 
<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<p>
  <strong>Слово:</strong>
  <%= @card.original_text %>
</p>
 
<p>
  <strong>Перевод:</strong>
  <%= @card.translated_text %>
</p>

<p>
  <strong>Дата повторения:</strong>
  <%= @card.review_date %>
</p>

<%= link_to 'Edit', edit_card_path(@card) %>
<%= link_to 'Back', cards_path %>

app/views/home/index.html.erb
<p style="font-size: 22px;">
Первый в мире удобный менеджер флеш-карточек. Именно так.
</p>

<% if @card.nil? %>
  Друг, приходи завтра
<% else %>
  <p>
    <strong>Слово:</strong>
    <%= @card.original_text %>
  </p>

  <p>
    <strong>Дата повторения:</strong>
    <%= @card.review_date %>
  </p>

  <%= form_tag("home/check", method: "post") do %>
  <%= label_tag(:translated_text, "Перевод:") %>
  <%= text_field_tag(:translated_text) %>
  <%= hidden_field_tag :card_id, @card.id %>
  <%= submit_tag("Проверь себя") %>
  <% end %>
<% end %>

    <% flash.each do |name, msg| -%>
      <%= content_tag :div, msg, class: name %>
    <% end -%>


  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Флэшкарточкер</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<section id="container">

    <header class="clearfix">
      <h1>Флэшкарточкер</h1>
      <ul class="navigation-links">
        <li><%= link_to "Все карточки", cards_path %></li>     
        <li><%= link_to "Добавить карточку", new_card_path %></li>
      </ul>
    </header>
  </section>
<section>
<%= yield %>
</section>

</body>
</html>